version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sofastream-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123123
      POSTGRES_DB: sofastream
    ports:
      - "5432:5432"
    volumes:
      - postgres_sofa_stream_data:/var/lib/postgresql/data

volumes:
  postgres_sofa_stream_data:
